"""Reproduce-the-filing reconciliation against INDEPENDENT ground truth.

The other tests read the same companyfacts-derived `facts` table the store is
built from, so they cannot catch a systematic wrong-tag / wrong-period / sign
error in the mapping. This check uses a different artifact entirely: the SEC-
rendered financial statements that ship with each filing as

    https://www.sec.gov/Archives/edgar/data/<cik>/<accession-no-dashes-removed>/Financial_Report.xlsx

We extract the headline lines straight off the rendered statements and assert
the store reproduces each one AS OF that filing's filing_date.

What this validates: that the pipeline reproduces the numbers a human sees in the
filing's rendered statements. What it does NOT validate: the correctness of the
underlying XBRL itself (rendered statements are built from the same XBRL).

Apple reports its statements in MILLIONS; the rendered values are scaled by 1e6
to full dollars. A wrong scale would make every assertion fail loudly.
"""
from __future__ import annotations

import io
from dataclasses import dataclass
from datetime import date
from pathlib import Path

import openpyxl

from .ingest import SecClient, DEFAULT_CACHE, cik10
from .query import point_in_time
from .store import TABLE

SCALE = 1_000_000  # Apple statements are in millions

# Fixed set of recent 10-Ks that ship Financial_Report.xlsx (FY2021–FY2024).
@dataclass(frozen=True)
class FilingTarget:
    fiscal_year: int
    accession_no: str
    filing_date: date


TARGETS = [
    FilingTarget(2024, "0000320193-24-000123", date(2024, 11, 1)),
    FilingTarget(2023, "0000320193-23-000106", date(2023, 11, 3)),
    FilingTarget(2022, "0000320193-22-000108", date(2022, 10, 28)),
    FilingTarget(2021, "0000320193-21-000105", date(2021, 10, 29)),
]

# headline metric -> (sheet-title contains, exact row label, store concept)
# labels are matched after normalization (see _norm).
HEADLINES = [
    ("revenue",             "STATEMENTS OF OPER", "net sales",                              "revenue"),
    ("net_income",          "STATEMENTS OF OPER", "net income",                             "net_income"),
    ("total_assets",        "BALANCE SHEETS",     "total assets",                           "total_assets"),
    ("total_liabilities",   "BALANCE SHEETS",     "total liabilities",                      "total_liabilities"),
    ("total_equity",        "BALANCE SHEETS",     "total shareholders' equity",             "total_equity"),
    ("operating_cash_flow", "STATEMENTS OF CASH", "cash generated by operating activities", "operating_cash_flow"),
]


def _norm(s: str) -> str:
    return (s.replace("\xa0", " ").replace("’", "'").strip().lower())


def financial_report_url(cik: int | str, accession_no: str) -> str:
    return (f"https://www.sec.gov/Archives/edgar/data/{int(cik)}/"
            f"{accession_no.replace('-', '')}/Financial_Report.xlsx")


def fetch_financial_report(cik: int | str, accession_no: str,
                           cache_dir: Path = DEFAULT_CACHE,
                           client: SecClient | None = None,
                           refresh: bool = False) -> Path:
    """Download (and cache) the rendered statements workbook for one filing."""
    cache_dir.mkdir(parents=True, exist_ok=True)
    path = cache_dir / f"Financial_Report_{cik10(cik)}_{accession_no}.xlsx"
    if path.exists() and not refresh:
        return path
    client = client or SecClient()
    path.write_bytes(client.get_bytes(financial_report_url(cik, accession_no)))
    return path


def extract_headlines(xlsx_path: Path) -> dict[str, float]:
    """Pull the headline lines (current period = first data column) in full dollars."""
    wb = openpyxl.load_workbook(xlsx_path, read_only=True, data_only=True)
    # Pre-resolve which sheet to use for each title fragment (first match wins,
    # and we skip parenthetical "(Pa..." companion sheets).
    by_fragment: dict[str, str] = {}
    for title in wb.sheetnames:
        up = title.upper()
        if "(PA" in up:
            continue
        for _, frag, _, _ in HEADLINES:
            if frag in up and frag not in by_fragment:
                by_fragment[frag] = title

    out: dict[str, float] = {}
    for metric, frag, label, _concept in HEADLINES:
        ws = wb[by_fragment[frag]]
        want = _norm(label)
        for row in ws.iter_rows(values_only=True):
            cell = row[0]
            if isinstance(cell, str) and _norm(cell) == want:
                value = row[1]  # current period is the first data column
                if isinstance(value, (int, float)):
                    out[metric] = float(value) * SCALE
                break
    return out


@dataclass
class ReconResult:
    fiscal_year: int
    metric: str
    rendered: float
    store: float | None

    @property
    def matched(self) -> bool:
        return self.store is not None and abs(self.rendered - self.store) <= 1.0


def reconcile(con, cik: int | str = 320193, targets=TARGETS,
              client: SecClient | None = None) -> list[ReconResult]:
    """For each target filing, compare rendered headlines to the store's value
    known AS OF that filing's filing_date (most-recent annual figure)."""
    client = client or SecClient()
    results: list[ReconResult] = []
    for t in targets:
        path = fetch_financial_report(cik, t.accession_no, client=client)
        rendered = extract_headlines(path)
        for metric, _frag, _label, concept in HEADLINES:
            r = point_in_time(con, concept, t.filing_date, periodicity="annual")
            store_val = None if r is None else r.value
            results.append(ReconResult(t.fiscal_year, metric, rendered[metric], store_val))
    return results


if __name__ == "__main__":
    from .store import build_store
    con = build_store()
    for res in reconcile(con):
        flag = "OK " if res.matched else "MISMATCH"
        sv = "None" if res.store is None else f"{res.store/1e9:,.3f}B"
        print(f"  [{flag}] FY{res.fiscal_year} {res.metric:20s} "
              f"rendered={res.rendered/1e9:,.3f}B store={sv}")
